apiVersion: v1
kind: Namespace
metadata:
  name: aks-periscope
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aks-periscope-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aks-periscope-role
rules:
- apiGroups: ["","metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["aks-periscope.azure.github.com"]
  resources: ["diagnostics"]
  verbs: ["get", "watch", "list", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aks-periscope-role-binding
subjects:
- kind: ServiceAccount
  name: aks-periscope-service-account
roleRef:
  kind: ClusterRole
  name: aks-periscope-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aks-periscope-role-binding-view
subjects:
- kind: ServiceAccount
  name: aks-periscope-service-account
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aks-periscope
  labels:
    app: aks-periscope
spec:
  selector:
    matchLabels:
      app: aks-periscope
  template:
    metadata:
      labels:
        app: aks-periscope
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: aks-periscope-service-account
      hostPID: true
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
      - name: aks-periscope
        image: aks-periscope
        securityContext:
          privileged: true
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: containerlogs-config
        - configMapRef:
            name: kubeobjects-config
        - configMapRef:
            name: nodelogs-config
        - secretRef:
            name: azureblob-secret
        volumeMounts:
        - mountPath: /aks-periscope
          name: aks-periscope-storage
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "2000Mi"
            cpu: "1000m"
      volumes:
      - name: aks-periscope-storage
        hostPath:
          path: /var/log/aks-periscope
          type: DirectoryOrCreate
---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: containerlogs-config
data:
  DIAGNOSTIC_CONTAINERLOGS_LIST: kube-system
---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: kubeobjects-config
data:
  DIAGNOSTIC_KUBEOBJECTS_LIST: kube-system/pod kube-system/service kube-system/deployment
---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: nodelogs-config
data:
  DIAGNOSTIC_NODELOGS_LIST: /var/log/azure/cluster-provision.log /var/log/cloud-init.log
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: diagnostics.aks-periscope.azure.github.com
spec:
  group: aks-periscope.azure.github.com
  versions:
  - name: v1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            dns:
              type: string
            networkoutbound:
              type: string
  scope: Namespaced
  names:
    plural: diagnostics
    singular: diagnostic
    kind: Diagnostic
    shortNames:
    - apd
