apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aks-periscope
  labels:
    app: aks-periscope
spec:
  selector:
    matchLabels:
      app: aks-periscope
  template:
    metadata:
      labels:
        app: aks-periscope
    spec:
      serviceAccountName: aks-periscope-service-account
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: aks-periscope
        image: periscope-linux
        securityContext:
          privileged: true
        imagePullPolicy: Always
        env:
        - name: HOST_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        envFrom:
        - configMapRef:
            name: diagnostic-config
        - secretRef:
            name: azureblob-secret
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: resolvlog
          mountPath: /run/systemd/resolve
        - name: etcvmlog
          mountPath: /etchostlogs
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "2000Mi"
            cpu: "1000m"
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: resolvlog
        hostPath:
          path: /run/systemd/resolve
      - name: etcvmlog
        hostPath:
          path: /etc
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aks-periscope-win
  labels:
    app: aks-periscope
spec:
  selector:
    matchLabels:
      app: aks-periscope
  template:
    metadata:
      labels:
        app: aks-periscope
    spec:
      serviceAccountName: aks-periscope-service-account
      hostPID: true
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: aks-periscope
        image: periscope-windows
        imagePullPolicy: Always
        env:
        - name: HOST_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        envFrom:
        - configMapRef:
            name: diagnostic-config
        - secretRef:
            name: azureblob-secret
        volumeMounts:
        - name: k
          mountPath: /k
        - name: azuredata
          mountPath: /AzureData
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "2000Mi"
            cpu: "1000m"
      volumes:
      - name: k
        hostPath:
          path: /k
      - name: azuredata
        hostPath:
          path: /AzureData
